name: student_tab
description: "EduForge Student Tab - Android Tablet"
publish_to: 'none'
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  eduforge_core:
    path: ../eduforge_core
  supabase_flutter: ^2.9.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  go_router: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
